### ISSUE TITLE
Placeholder Image Improvement

### ISSUE THREAD

**Issue by valpizzo** [TempleOfArtemis/FEC_main#81]
#### Description
The thumbnail image is set to an empty string, '', and then switched to a placeholder image if it is an empty string. Skip the empty string step to reduce lines of code.
#### Files
https://github.com/TempleOfArtemis/FEC_main/blob/67594d27c07f8b71da1971274616fd34cd304bee/client/src/Item-Overview/subcomponents/Checkout.jsx#L31-L37
#### Tasks (optional)
- [ ] If the thumbnail image doesn't exist in line 32, set thumbnailURL to the placeholder image
- [ ] Delete the else statement in lines 35 - 37
- [ ] Split line 32 into at least two lines for better readability
