### ISSUE TITLE
UI Improvements: Star Rating, Star Filtration, Review Window Size... 

### ISSUE THREAD

**Issue by SoniaAnn** [TempleOfArtemis/FEC_main#91]
@benjaminlthornton 
Hey Ben! **Great Job!** Your component is impressive!

## Description
I've found some small UI improvements that you might want to look into.

### Star Rating Rounding to the *nearest* quarter. 
I noticed that the star ratings do not round to the nearest quarter, rather the fill seems to render based on hitting  a threshold. I think this would be an improvement because the visual related to the rating says a lot. It is underselling the rating by up-to a quarter of a star (3.9 is represented as 3.75, rather than 4.0)

#### Tasks/ Suggestions from a fellow reviews widgeter
Instead of thresholds, round to the nearest quarter.
https://stackoverflow.com/questions/1553704/round-to-nearest-25-javascript

#### Files
https://github.com/TempleOfArtemis/FEC_main/blob/67594d27c07f8b71da1971274616fd34cd304bee/client/src/shared/StarRating.jsx#L13-L23

### Implementing Star Filtering
I notice that you've made the links look clickable but the reviews don't actually sort. This can be confusing for a user. I think it could be a great addition to the already extensive functionality of your component.

#### Files
(on hover functionality)
https://github.com/TempleOfArtemis/FEC_main/blob/67594d27c07f8b71da1971274616fd34cd304bee/client/src/Ratings-Reviews/RRcomponents/RatingSummary/RatingBreakdown/barChart.jsx#L9-L27
(function location)
https://github.com/TempleOfArtemis/FEC_main/blob/67594d27c07f8b71da1971274616fd34cd304bee/client/src/Ratings-Reviews/RRcomponents/RRapp.jsx#L8-L11

#### Tasks/ Suggestions from a fellow reviews widgeter

- [ ]  set a state variable (preferably an array) that holds the star filtration that is clicked on (arrays work well for the additive component of filtration
- [ ] make an onclick that sets state to push the star label (5, 4...etc.).
- [ ] obtain all messages with a high count in your request params
- [ ] sort those messages using the array for filtering
- [ ] remember to add toggle functionality! (quite a challenge! and you may want to consider an object structure instead because getting is constant time)

### Larger Reviews Window
I notice that the size of the reviews list is capped at about 2 reviews at a time before scroll. I think it would be nice to add a bit more height to that section to allow for more reviews to be seen at a time.

#### Tasks/ Suggestions from a fellow reviews widgeter

- [ ] If you don't already have one, make a styled component for review list
- [ ] set height to the height of your component container/ height of your review breakdown/ whatever you prefer that is longer. 

#### Files
https://github.com/TempleOfArtemis/FEC_main/blob/67594d27c07f8b71da1971274616fd34cd304bee/client/src/Ratings-Reviews/RRcomponents/ReviewList/ReviewList.jsx#L70-L95

## ScreenShot
![Screen Shot 2022-06-04 at 10 45 12 AM](https://user-images.githubusercontent.com/97041979/172012903-8f348343-f764-4fc3-8187-88d116cef02a.png)

**Comment by Diza41a** [comment]
Star rating is supposed to floor to lower quarter per business doc, I believe. Really loving your professional and extensive approach to writing issues Sonia, thank you👍

**Comment by benjaminlthornton** [comment]
Lengthened the review list, but didn't make it a styled component. Spent a lot of time converting from styled component to sass.
